### PR TITLE
Feature: Add flash in Scanner Modal

### PR DESCRIPTION
**Pull request by fabiiretro**
Enabling the option to use the phones flash can increase the reliability of the scanner function*.
For that I added a new button to toggle this function. I also swapped positions of the canvas and the buttons because I felt like that UI would be more intuitive for mobile - that is optional and can be reverted before merging if you'd like. My color choice is also debatable.

Tested on mobile and desktop - desktop obviously has no effect.

I also thought about adding part 1 "search the Open Food Facts data base with text rather than barcode" from #56 but in a sense to input the "text barcode" instead of scanning it. Let me know if you have any thoughts about that

### CODE REVIEW

**Comment by fabiiretro** [comment]
Forgot to include your updated README -> should be fixed now

**Comment by paulzakin** [comment]
Thanks for the PR!

Code looks good, can you just post a quick screenshot of the UI changes so I can take a look? Thanks!

As for your idea on #56, I would need a mockup I think of what you mean.

**Comment by fabiiretro** [comment]
Sure thing. Took them on desktop and denied camera access, that's why that's blank
Screenshot From 2024-11-03 05-42-44
Screenshot From 2024-11-03 05-43-27
Screenshot From 2024-11-03 05-43-33

About #56 I threw together this. Not pretty, but it'll do for what I was thinking. Short: Use the Open Food Facts API without the need for the camera - i.e. skip the scanning of the barcode and input it yourself (they're usually printed below, at least in Germany)
image

Side note: I'm open about aesthetics/location of components.

**Comment by paulzakin** [comment]
Closing in favor of #212, which has all your code and some of mine

**Comment by paulzakin** [comment]
Merged and deployed with some styling tweaks. Thanks for the hard work!

I do not think I will add the barcode text entry, as I am concerned it will clutter the interface. However, if you want to submit a PR for it, I will to give it a look!

**Pull request closed without merging**
